apiVersion: v1
kind: Secret
metadata:
  name: job-tracker-api-secret
  namespace: job-tracker
type: Opaque
stringData:
  DATABASE_URL: "postgresql+psycopg://jobuser:REPLACE_WITH_PASSWORD@REPLACE_WITH_RDS_ENDPOINT:5432/jobtracker"
